### PR TITLE
feat: showcase form support

### PR DESCRIPTION
**Pull request by TurtIeSocks**
Adds backwards compatible support for https://github.com/UnownHash/Golbat/pull/188

### CODE REVIEW

**Comment by comstud** [comment]
Not seeing correct form it seems. I'll debug later today/tonight. Thanks!

**Comment by TurtIeSocks** [comment]
The db entry and what's being sent to the client aren't matching or it's being collected incorrectly from protos?

**Comment by comstud** [comment]
I was just dumb and failed to actually start the new version properly. It works! :)

**Comment by comstud** [comment]
2 different pokestops, showing correct forms now:

image
image

**Pull request merged**
