### PR TITLE
Bring back `scan_zone_choose` text

### PR DESCRIPTION
**Pull request by kamieniarz**
`scan_zone_choose` text was removed with https://github.com/WatWowMap/ReactMap/pull/810
So here's my (proly ulgy and wrong) PR to bring it back. Works for me 🤷‍♂️

### CODE REVIEW

**Comment by TurtIeSocks** [comment]
Thanks for the contribution! A little overkill though, you could revert all these commits and just do something like:
```jsx
          secondary={t(mode === 'scanZone' ? 'scan_zone_choose' : 'scan_next_choose')}
```

**Comment by kamieniarz** [comment]
Obviously that works 😅 Thanks!

**Comment by TurtIeSocks** [comment]
> Obviously that works 😅 Thanks!

Great! Just fix the prettier issue `yarn prettier:fix` and I'll get this merged.

**Review by TurtIeSocks — APPROVED** [review]
Thank you for the bug fix!

**Pull request merged**
