### PR TITLE
Filter by Quest Conditions

### PR DESCRIPTION
**Pull request by TurtIeSocks**
- Filter quests by their conditions now if a reward has multiple conditions
- Rework available, returns an object instead now for future expandability
- questConditions gql api update
- version bump
- Make better use of promise.all in getAvailable pokestops method to reduce query time
Screen Shot 2022-06-09 at 1 04 58 AM
s

### CODE REVIEW

**Review by Mygod — APPROVED** [review]
life changing wish could approve more

**Comment by pjorritsma** [comment]
My community would love this feature, alot of  requests about it.

**Comment by ReuschelCGN** [comment]
works nice - translation for **"Earn 3 Candies exploring with your buddy"** is missing ....

**Comment by TurtIeSocks** [comment]
Did you regenerate locales? This commit fixes it https://github.com/WatWowMap/ReactMap/commit/005e850e092cdea58d09b22e0ebbf7839203e87f

**Pull request merged**
