### PR TITLE
Move Coords to Client Side Settings

### PR DESCRIPTION
**Pull request by plinytheelder**
Don't default everything to a spoofer map. Move Coords to client side settings.

### CODE REVIEW

**Review by TurtIeSocks — CHANGES_REQUESTED** [review]
Dayummm, look at you! Only feedback that comes to mind at first glance is please add english translation keys into the base locales file. There are some "automatic" translations done when keys are missing, so it appears fine when browsing in English, but it's important to maintain the keys in the json for other locales that want to add them. `enablePokemonPopupCoords` => `enable_pokemon_popup_coords` in the `en.json` file.

Great job, thanks for the PR!

**Comment by plinytheelder** [comment]
no problemo! let me know if I did it right this time.

**Review by TurtIeSocks — APPROVED** [review]

**Comment by Fabio1988** [comment]
Could it be that this is completly disabling the possibility to disable that feature for the admin?

For me e.g I would nerver give user the possibility to show the coords

**Comment by TurtIeSocks** [comment]
Someone can PR something like this:
https://github.com/WatWowMap/ReactMap/blob/main/server/src/services/ui/clientOptions.js#L96-L98

**Comment by ReuschelCGN** [comment]
like this i build this morning?
https://github.com/ReuschelCGN/ReactMap/blob/666ce7194a090f1e8144f746efa26eac75ca4155/server/src/services/ui/clientOptions.js#L106

**Pull request merged**
