### PR TITLE
Swap login button color to green

### PR DESCRIPTION
**Pull request by lenisko**
I open the discussion!

...

Screenshots below

### CODE REVIEW

**Comment by TurtIeSocks** [comment]
Interesting choice.

**Comment by lenisko** [comment]
Broken one ;)

**Comment by lenisko** [comment]
Someone reused component named `DiscordLogin` to `Join` and few other places :joy:

**Comment by lenisko** [comment]
Added screenshot as an example. I need some IDE for JS...

**Comment by TurtIeSocks** [comment]
Seems very bright. How does it look in dark mode? Try using the `color="success"` prop to use the theme green.

**Comment by lenisko** [comment]
Screenshot 2023-08-15 at 01 16 26
Screenshot 2023-08-15 at 01 16 23

**Comment by lenisko** [comment]
Got scolded by my personal UX... Apparently, should use PRIMARY and SECONDARY colors...

**Review by clburlison — APPROVED** [review]

**Comment by roundaboutluke** [comment]
Discord’s blurple change recently to #5865F2. While I’m not a fan of the green either way it would be better to stick within the branding guidelines and use #57F287 for that.

https://discord.com/branding

**Comment by lenisko** [comment]
Well, it makes sense, but `#57F287` is ultra bright 😓

**Comment by TurtIeSocks** [comment]
Agreed, that Discord green is brutal on the eyes.

**Comment by roundaboutluke** [comment]
God even on black it’s bad. They all are just tried them all. I’d say just update blurple and be done with it. Custom login page can be used for anything beyond really and I do agree some sort of default distinction is good for new mappers to get going with.

**Comment by TurtIeSocks** [comment]
Resolved in #826, apologies @lenisko. Forgot to take it out when I was playing with it while we were talking.

**Pull request closed without merging**
