### PR TITLE
feat: interactive marker opacity

### LINKED ISSUE #683: Visual indication of a despawning mon/invasion
Maybe can make a mon semi-transparent if it is going to despawn within a minute (if timer is verified)? :)

### PR DESCRIPTION
**Pull request by TurtIeSocks**
- Sets opacity of the marker based on the despawn time
- Active for pokemon, invasions, and raids
- Follows these rules:
  - < 1 min = 25%
  - < 5min = 50%
  - < 10min = 75%
  - More than 10min = 100%
- This does not interact with the marker memoization equality checks for performance reasons. In order to update opacity, you'll have to move the marker off screen and back again to rerender it

Resolves #683

### CODE REVIEW

**Comment by kamieniarz** [comment]
Please make it optional for users but switched off by default

**Comment by plinytheelder** [comment]
my users and I agree with @kamieniarz. this should be optional.

**Comment by TurtIeSocks** [comment]
All of my users have loved it so far. PRs will be accepted though 👍

**Comment by plinytheelder** [comment]
can look into it. a variable should be easy.

but since I'm leaving for work, setting all these variables to 1 is an ez bandaid fix.

https://github.com/WatWowMap/ReactMap/blob/develop/src/services/functions/getOpacity.js

**Pull request merged**
