### PR TITLE
Discord max field size 1024 exceeded fix

### PR DESCRIPTION
**Pull request by jepke**
There are more elegant ways to fix this but its a fix.

### CODE REVIEW

**Comment by jepke** [comment]
nvm this breaks even more... WIP

**Comment by TurtIeSocks** [comment]
Instead of setting this in the discord client, which sets the permissions for the user across the entire site, you'll want to limit it in the embed building function:
https://github.com/WatWowMap/ReactMap/blob/main/server/src/services/logUserAuth.js

**Comment by TurtIeSocks** [comment]
I'm doing something similar here for scanNext/scanZone logging you can reference:
https://github.com/WatWowMap/ReactMap/blob/38c25266a4cc9e15d6ff2a5c6d701352a3895885/server/src/services/api/scannerApi.js#L167

**Comment by jepke** [comment]
fix for #617

**Review by TurtIeSocks — APPROVED** [review]

**Pull request merged**
