### PR TITLE
Add Fort Power Ups

### PR DESCRIPTION
**Pull request by TurtIeSocks**
- Fort power ups
- Points/Day/Days translation keys
- Adjust some eslint rules
- Fix some translation issues

### CODE REVIEW

**Comment by TurtIeSocks** [comment]
Do people care about being able to filter these?

**Comment by kamieniarz** [comment]
Gyms only, right? I can't see power ups for pokestops

**Comment by TurtIeSocks** [comment]
Screen Shot 2022-04-17 at 1 04 18 PM
Pokestops too

**Comment by kamieniarz** [comment]
Ugh I don't see any nearby so can't confirm but anyway Invasions are broken with this PR

**Comment by Fabio1988** [comment]
You can filter them in RDM ;)

**Pull request merged**
