### PR TITLE
fix a typo: availble -> available

### PR DESCRIPTION
**Pull request by ccev**
my reactmap gave me this error and i quickly fixed it with the github editor! so there might be other references i missed

### CODE REVIEW

**Comment by TurtIeSocks** [comment]
This is intentional due to a misspelling in RDM's db schema.

**Comment by Fabio1988** [comment]
Not in RDM development branch

**Comment by ccev** [comment]
I am getting an error for this

```
 GraphQL Error: Cannot query field "availble_slots" on type "Gym". Did you mean "available_slots"?
```
and using MAD.

**Comment by TurtIeSocks** [comment]
Tell your users to refresh their browser :lappy:

**Comment by ccev** [comment]
ahh, got it. it's confusing me.

**Pull request closed without merging**
