### PR TITLE
splits event stop permissions

### LINKED ISSUE #633: Event Stops do not respect incident perms
Event stops are seen for everyone.

auth Config:
- Without any perm restrictions:
  - map
  - gyms
  - pokestops
  - raids
- all other perms restricted with donor role id

PS: I then tried also to restrict pokestops with donor id, but it seems it's still visible for non registered user. My map is visible for everyone visiting, no login needed. I only restrict premium features like pokemon, invasions, quests, etc

### PR DESCRIPTION
**Pull request by TurtIeSocks**
**Breaking-ish changes**
- Adds a new perm for event stops
- Version bump
- Forced logout for your users
- New perm images and subtitle
- Routing fixes for vite usage
- Fixes event tooltip 

Resolves #633

### CODE REVIEW

**Comment by kamieniarz** [comment]
I ran some tests with accounts with different roles and permissions and all seems fine to me. Thanks!

**Comment by kamieniarz** [comment]
Shit, actually I get this error when I enabled all pokestops:
`Invariant Violation: 34 (see https://github.com/apollographql/invariant-packages)`
One of my users also reported me that

**Comment by TurtIeSocks** [comment]
Not sure what that could mean and not seeing it myself when I enable all pokestops.

**Comment by kamieniarz** [comment]
In my case I received that error right after I enabled all pokestops - I had to clear cookies and restore my settings and I can't reproduce that error now.

**Comment by TurtIeSocks** [comment]
Okay managed to force a similar error, though a different combinations of switches. Pushed the fix.

**Comment by kamieniarz** [comment]
Works now, thanks!

**Comment by Fabio1988** [comment]
Works :)

**Review by Fabio1988 — APPROVED** [review]

**Pull request merged**
